// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19/09/2025, 22:50:47
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/dev/allanstore/components/**/*.{vue,js,jsx,mjs,ts,tsx}","components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/dev/allanstore/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/dev/allanstore/plugins/**/*.{js,ts,mjs}","C:/dev/allanstore/composables/**/*.{js,ts,mjs}","C:/dev/allanstore/utils/**/*.{js,ts,mjs}","C:/dev/allanstore/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/dev/allanstore/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/dev/allanstore/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/dev/allanstore/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;